clients {
  base {
    http {
      timeout = "30s"
      timeout = ${?CLIENT_BASE_TIMEOUT}
    }
  }
  permissionVerifier {
    baseUrl = "localhost:3000"
    baseUrl = ${?CLIENT_PERMISSION_VERIFIER_BASE_URL}
  }
}